### ISSUE TITLE
support a non-telegram form of communication

### ISSUE THREAD

**Issue by nellePoint** [reiryuki/One-UI-Core-Magisk-Module#2]
yeah i know, it will be closed immediately.

not everyone uses or trusts signal and its kind of rediculous to assume so. personally i refuse to use it when there is a perfect good and superior issue system built right into the repo (you can disable that yanno!)

anyway, even a matrix room would work i guess.

**Comment by reiryuki** [comment]
you can use discussion tab instead of issue tab
